spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.h2.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

weather:
  cron: "0 15 * * * *"